version: "3.8"

networks:
  dev-network:
    driver: overlay
    name: find-dev
  main-network:
    driver: overlay
    name: find-peer${FIND_PEER_INDEX}
  ipfs-network:
    driver: bridge
    name: find-ipfs

volumes:
  ctx:
    driver: local
    driver_opts:
      type: none
      device: ../../
      o: bind
  ipfs-volume:
    name: find-ipfs-peer${FIND_PEER_INDEX}

services:

  app:
    image: find.app
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        workdir:  /ctx/find/bin/app
    command: tail -f /dev/null
    # command: bash f dev
    ports:
      - 840${FIND_PEER_INDEX}:8400
      - 400${FIND_PEER_INDEX}:400${FIND_PEER_INDEX}
      - 500${FIND_PEER_INDEX}:5001
      - 880${FIND_PEER_INDEX}:8080
      - 881${FIND_PEER_INDEX}:8081
    environment:
      - FIND_PEER_INDEX=${FIND_PEER_INDEX}
      - DISPLAY=$DISPLAY
    networks:
      main-network:
      ipfs-network:
      dev-network:
    volumes:
      - ./app/volumes/root${FIND_PEER_INDEX}:/root
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M